version: '3'
services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: monki
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 2912
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
#      - ./init-scripts:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monki
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2912
